phone_book/phone_book/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view, search_view
from django.conf.urls.static import static
from phone_book import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('search', search_view, name='search'),
    path('', include('phone_book_contacts.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phone_book/phone_book_contacts/urls.py
from django.urls import path

app_name = 'phone_book_contacts'
from .views import *

urlpatterns = [
    path('delete-contact', delete_contact_component_view, name='delete'),
    path('show-contact', show_contact_component_view, name='show'),
    path('add-contact-by-form', add_contact_by_form_component_view, name='add_form'),
    path('add-contact-by-file', add_contact_by_file_view, name='add_file'),
    path('add-contact-by-file-in-search', add_contact_by_file_component_view_for_search, name='add_file_in_search'),
    path('search-contact', search_contact_component_view, name='search'),
]

phone_book/phone_book_contacts/models.py
from django.core.exceptions import ValidationError
from django.db import models
from phone_book_accounts.models import AnonymousAccount
import os
from django.db.models import Q


# Create your models here.


def contact_image_directory_path(instance, filename):
    base_name, ext = os.path.splitext(filename)
    return f'UserInFo/{instance}/{instance}{ext}'


class ContactManager(models.Manager):
    def search(self, anonymous_account, name='', family='', email='', phone='', num_company_or_home='', address='',
               ):
        lookup = Q(name__icontains=name) & Q(family__icontains=family) & Q(email__icontains=email) & Q(
            phone__icontains=phone) & Q(num_company_or_home__icontains=num_company_or_home) & Q(
            address__icontains=address)
        return anonymous_account.contact_set.filter(lookup).distinct()

    def get_max_id_or_1(self):
        id__max = self.aggregate(models.Max('id'))['id__max']
        if id__max is not None:
            id__max += 1
        return id__max or 1


class Contact(models.Model):
    name = models.CharField(max_length=20)
    family = models.CharField(max_length=20, blank=True, default='')
    email = models.EmailField(max_length=100, blank=True, default='')
    phone = models.CharField(max_length=10, blank=True, default='')
    num_company_or_home = models.CharField(max_length=20, blank=True, default='')
    address = models.TextField(max_length=400, blank=True, default='')
    image = models.ImageField(upload_to=contact_image_directory_path, blank=True, default='')
    anonymous_account = models.ForeignKey(AnonymousAccount, on_delete=models.CASCADE)

    objects = ContactManager()

    def __str__(self):
        return self.name


def set_name_and_folder_excel_file(instance, filename):
    baseName, extension = os.path.splitext(filename)
    return f'excel_file/{baseName}{extension}'


class ContactFile(models.Model):
    file = models.FileField(upload_to=set_name_and_folder_excel_file)

    def check_extension(self):
        name, extension = os.path.splitext(self.file.name)
        if extension == '.xlsx':
            return 'xlsx'
        if extension == '.csv':
            return 'csv'
        raise ValidationError('the file must be excel or csv')

phone_book/phone_book_contacts/forms.py
from django import forms
from phone_book_contacts.models import Contact, ContactFile


class AddForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        exclude = ['anonymous_account']

    def save(self, anonymous_account, commit=True):

        obj = super(AddForm, self).save(commit=False)
        obj.anonymous_account = anonymous_account
        obj.save()


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ContactFile
        fields = '__all__'

phone_book/phone_book_contacts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.clickjacking import xframe_options_exempt
from .forms import AddForm, AddFileForm
from phone_book_contacts.models import Contact
from phone_book_accounts.models import AnonymousAccount
from sqlalchemy import create_engine
from django.http import HttpResponse
import pandas as pd
from phone_book import settings
from phone_book_tools.tools import get_equal_items_list_one_in_list_tow, is_extension_xlsx, is_extension_csv
from django.contrib import messages
from django.urls import reverse

# Create your views here.


user = settings.DATABASES['default']['USER']
password = settings.DATABASES['default']['PASSWORD']
database_name = settings.DATABASES['default']['NAME']

database_url = 'mysql://{user}:{password}@localhost:3306/{database_name}'.format(
    user=user,
    password=password,
    database_name=database_name,
)
engine = create_engine(database_url, echo=False)


def show_contact_component_view(request):
    username = request.COOKIES.get('username')
    anonymous_account = AnonymousAccount.objects.filter(username=username).first()
    contact_qu = Contact.objects.filter(anonymous_account=anonymous_account)

    context = {
        'contact_qu': contact_qu
    }
    return render(request, template_name='contact/show_contact_component.html', context=context)


def search_contact_component_view(request):
    kwargs = dict()
    kwargs['name'] = request.GET.get('name') or ''
    kwargs['family'] = request.GET.get('family') or ''
    kwargs['email'] = request.GET.get('email') or ''
    kwargs['phone'] = request.GET.get('phone') or ''
    kwargs['num_company_or_home'] = request.GET.get('num') or ''
    kwargs['address'] = request.GET.get('address') or ''
    username = request.COOKIES.get('username') or ''
    anonymous_account = AnonymousAccount.objects.filter(username=username).first()
    contact_qu = Contact.objects.search(anonymous_account, **kwargs)
    print('search_contact_component_view: ', request.GET, '  ', contact_qu, ' ', kwargs)

    context = {
        'contact_qu': contact_qu
    }
    return render(request, template_name='contact/search_contact_component.html', context=context)




def delete_contact_component_view(request):
    print(request.POST)
    username = request.COOKIES.get('username')
    anonymous_account = AnonymousAccount.objects.filter(username=username).first()
    list_pk = request.POST.getlist('PK')
    user_info = anonymous_account.contact_set.all()
    user_info.filter(pk__in=list_pk).delete()

    return HttpResponse('the action delete is completely successed')


@xframe_options_exempt
def add_contact_by_form_component_view(request):
    add_form = AddForm(request.POST or None, request.FILES or None)

    if add_form.is_valid():
        print("request.FILES['file']: ", request.FILES)
        username = request.COOKIES.get('username')
        anonymous_account = AnonymousAccount.objects.filter(username=username).first()
        add_form.save(anonymous_account)

    context = {
        'add_form': add_form
    }
    return render(request, template_name='contact/add_contact_by_form_component.html', context=context)



def add_contact_by_file_view(request):
    add_file_form = AddFileForm(request.POST or None, request.FILES or None)
    if add_file_form.is_valid():
        try:
            if is_extension_xlsx(str(add_file_form.cleaned_data.get('file'))):
                df = pd.read_excel(add_file_form.files['file'])
            elif is_extension_csv(str(add_file_form.cleaned_data.get('file'))):
                df = pd.read_csv(add_file_form.files['file'])
            else:
                messages.error(request, 'فایل باید اکسل یا سی اس وی باشد')
                return redirect(reverse('home'))
            data_frame_key_list = df.keys()
            field_list = ['name', 'family', 'email', 'phone', 'num_company_or_home', 'address']
            data_frame_key_list, fields_not_in_data_frame_keys_list = get_equal_items_list_one_in_list_tow(
                field_list, data_frame_key_list)
            if len(fields_not_in_data_frame_keys_list) != 0:
                messages.add_message(request, messages.ERROR,
                                     f'این عنوان {fields_not_in_data_frame_keys_list} در  فایل وجود ندارد')
                return redirect('/')
            username = request.COOKIES.get('username')
            anonymous_account = AnonymousAccount.objects.filter(username=username).first()
            df['anonymous_account_id'] = anonymous_account.id
            df.index += Contact.objects.get_max_id_or_1()
            df.to_sql(Contact._meta.db_table, con=engine, if_exists='append', index_label='id')
            request.FILES['file'] = None

        except:
            messages.add_message(request, messages.ERROR,
                                 f'فایل ذخیره نشد لطفا با پشتیبانی زنگ بزنید')

    # return redirect(f'{request.META.get("HTTP_REFERER")}')
    return redirect('/')


def add_contact_by_file_component_view_for_search(request):
    add_file_form = AddFileForm(request.POST or None, request.FILES or None)
    context = {
        'add_file_form': add_file_form,
    }
    if add_file_form.is_valid():
        try:
            df = pd.read_excel(add_file_form.files['file'])
            username = request.COOKIES.get('username')
            anonymous_account = AnonymousAccount.objects.filter(username=username).first()
            df['anonymous_account_id'] = anonymous_account.id
            df.to_sql(Contact._meta.db_table, con=engine, if_exists='append', index_label='id')
        except:
            df = pd.read_excel(add_file_form.files['file'])
            data_frame_key_list = df.keys()
            field_list = ['name', 'family', 'email', 'phone', 'num_company_or_home', 'address']
            data_frame_key_list, fields_not_in_data_frame_keys_list = get_equal_items_list_one_in_list_tow(
                field_list, data_frame_key_list)
            add_file_form.add_error('file', f'این عنوان {fields_not_in_data_frame_keys_list} در  فایل وجود ندارد')

    return render(request, template_name='contact/add_contact_by_file_component_in_search.html', context=context)

phone_book/phone_book_contacts/templates/contact/add_contact_by_file_component.html
<div>
    <dialog style="height: 150px; overflow: auto">
        <form action="{% url 'contact:add_file' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} style="color:{{ message.tags }}"{% endif %}>
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            {{ add_file_form }}
            <button type="submit">ارسال</button>
        </form>
    </dialog>
</div>

phone_book/phone_book_contacts/templates/contact/add_contact_by_file_component_in_search.html
<div>
    <dialog style="height: 150px; overflow: auto">
        <form  action="{% url 'contact:add_file' %}?{{ request.GET.urlencode}}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{add_file_form}}
            <button type="submit">ارسال</button>
        </form>
    </dialog>
</div>

phone_book/phone_book_contacts/templates/contact/add_contact_by_form_component.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/iframe.css' %}">
</head>
<body>
<div>
    <form action="{% url 'contact:add_form' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ add_form }}
{#        <input type="text" placeholder="اسم" name="name">#}
{##}
{#        <input type="text" placeholder="فامیلی" name="family">#}
{##}
{#        <input type="text" placeholder="تلفن" name="phone">#}
{##}
{#        <input type="text" placeholder="تلفن خانه یا شرکت" name="num_company_or_home">#}
{##}
{#        <input type="text" placeholder="ایمیل" name="email">#}
{##}
{#        <input type="text" placeholder="شهر">#}
{##}
{#        <textarea rows="9" placeholder="ادرس" name="address"></textarea>#}
        <br>
        <button  type="submit">add</button>

    </form>
</div>

</body>
</html>

phone_book/phone_book_contacts/templates/contact/search_contact_component.html
{% load static %}
<section onclick="checkSizeSction()">
        {% for contact in contact_qu %}
        <div id="{{ contact.pk }}" onclick="selectItem({{ contact.pk }})">
            {% if contact.image %}
                <img src="{{ contact.image.url }}" alt="">
            {% else %}
                <img src="{% static 'image/user.jpg' %}" alt="">

            {% endif %}

            <p name="name">اسم: {{ contact.name }}</p>
            <p name="family">فامیلی: {{ contact.family }}</p>
            <p name="email" hidden>ایمیل: {{ contact.email }}</p>
            <p name="phone" hidden>تلفن: {{ contact.email }}</p>
            <p name="home" hidden>شماره خانه یا شرکت: {{ contact.num_company_or_home }}</p>
            <p name="address" hidden>ادرس: {{ contact.address }}</p>
            <input type="checkbox" hidden name="alist" value="{{ contact.pk }}">
        </div>
    {% endfor %}


    <!-- <iframe src="demo_iframe.htm" height="200" width="300" title="Iframe Example"></iframe>  -->
</section>

phone_book/phone_book_contacts/templates/contact/show_contact_component.html
{% load static %}
<section onclick="checkSizeSction()">
        {% for contact in contact_qu %}
        <div id="{{ contact.pk }}" onclick="selectItem({{ contact.pk }})">
            {% if contact.image %}
                <img src="{{ contact.image.url }}" alt="">
            {% else %}
                <img src="{% static 'image/user.jpg' %}" alt="">

            {% endif %}

            <p name="name">اسم: {{ contact.name }}</p>
            <p name="family">فامیلی: {{ contact.family }}</p>
            <p name="email" hidden>ایمیل: {{ contact.email }}</p>
            <p name="phone" hidden>تلفن: {{ contact.email }}</p>
            <p name="home" hidden>شماره خانه یا شرکت: {{ contact.num_company_or_home }}</p>
            <p name="address" hidden>ادرس: {{ contact.address }}</p>
            <input type="checkbox" hidden name="alist" value="{{ contact.pk }}">
        </div>
    {% endfor %}


    <!-- <iframe src="demo_iframe.htm" height="200" width="300" title="Iframe Example"></iframe>  -->
</section>